params = {"ch": "cH",
	  "ct": "cT",
	  "c6": "c6",
	  "cu": "cu",
	  "cd": "cd",
	  "cl": "cl",
	  "cww": "cWW",
	  "cb": "cB",
	  "chw": "cHW",
	  "chb": "cHB",
	  "ca": "cA",
	  "cg": "cG",
	  "chq": "cHQ",
	  "cphq": "cpHQ",
	  "chu": "cHu",
	  "chd": "cHd",
	  "chud": "cHud",
	  "chl": "cHL",
	  "cphl": "cpHL",
	  "che": "cHe",
	  "cub": "cuB",
	  "cuw": "cuW",
	  "cug": "cuG",
	  "cdb": "cdB",
	  "cdw": "cdW",
	  "cdg": "cdG",
	  "clb": "clB",
	  "clw": "clW",
	  "c3w": "c3W",
	  "c3g": "c3G",
	  "c2w": "c2W",
	  "c2b": "c2B",
	  "c2g": "c2G",
	  "tchw": "tcHW",
	  "tchb": "tcHB",
	  "tcg": "tcG",
	  "tca": "tcA",
	  "tc3w": "tc3W",
	  "tc3g": "tc3G",}



